name             'jeff-project'
maintainer       'Natan Vecchiarelli'
maintainer_email 'natevecc@gmail.com'
license          'MIT'
description      'Installs/Configures jeff-app'
long_description 'Installs/Configures jeff-app'
version          '0.1.0'

depends 'apt'
depends 'git'
depends 'build-essential'
depends 'nvm'
depends 'vim'
depends 'postgresql'
depends 'database'